### ISSUE TITLE
🔴  link do projeto #provihack

### ISSUE THREAD

**Issue by monteirocamis** [felipecro28/coleta-sustentavel-frontend#6]
Olá pessoal, qual é o link do projeto no surge ou vercel por exemplo ?}
@felipecro28 
obrigada
=)

**Comment by felipecro28** [comment]
> Olá pessoal, qual é o link do projeto no surge ou vercel por exemplo ?} @felipecro28 obrigada =)

Oi, @monteirocamis ! Eu não conhecia o surge, então quero te agradecer muito pela issue. Consegui fazer deploy do projeto por lá, e assim que passar tudo pela validação do hackaton, vou alterar a documentação do projeto para constar o link do deploy.

Por ora, segue por aqui:
coleta-sustentavel.surge.sh

Fique a vontade para reportar qualquer problema com o link do surge, ou qualquer dúvida que surgir com a aplicação.

Obrigado =)

**Comment by monteirocamis** [comment]
obaa que legal!! maginaa 
muito obrigada por correr atrás disso

**Comment by monteirocamis** [comment]
Ah @felipecro28  tem algo após logar? que eu tentei criar cadastro e nao abriu nada, é isso mesmo?

**Comment by felipecro28** [comment]
@monteirocamis nossa equipe sofreu uma baixa gigante e eu fiquei sozinho com a parte de desenvolvimento (front e back). algumas funcionalidades tiveram que ficar para depois do hacka, mas certeza que não demora muito e vou tocar esse projeto pra frente :)

**Comment by monteirocamis** [comment]
fica tranquilo xuxu, jaja voce encontra mais alguem pro time entao
sucessooo
